name: Test

on:
  push:
    tags-ignore:
      - '**'
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: [ '7.3', '7.4', '8.0' ]
        wp-versions: [ 'WordPress#5.9', 'WordPress#6.0' ]
        # wp-versions: [ 'WordPress#5.9', 'WordPress#6.0', 'WordPress' ]
    name: PHP ${{ matrix.php-versions }}  / ${{ matrix.wp-versions }} Test

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 14.x
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Npm install and build
        run: |
          npm ci
          npm run build

      - name: Composer install and set phpcs
        run: |
          composer install
          composer phpcs

      - name: Running lint check
        run: npm run lint

      - name: Install WordPress
        run: |
          WP_ENV_CORE=WordPress/${{ matrix.wp-versions }} WP_ENV_PHP_VERSION=${{ matrix.php-versions }} npm run wp-env start
          npm run wp-env run cli wp core version
          npm run wp-env run cli wp cli info

      - name: Running e2e tests
        run: npm run test:e2e
