name: Test and Deploy

on:
  push:
    branches-ignore:
      - '**'
    tags:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: [
          '7.3',
          '7.4',
          '8.0',
          '8.1',
        ]
        wp-versions: [
          'WordPress#5.9.5',
          'WordPress#6.0.3',
          'WordPress#6.1.1',
          'WordPress',
        ]
    name: PHP ${{ matrix.php-versions }}  / ${{ matrix.wp-versions }} Test

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 14.x
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Npm install and build
        run: |
          npm ci
          npm run build

      - name: Composer install and set phpcs
        run: |
          composer install
          composer phpcs

      - name: Running lint check
        run: npm run lint

      - name: Install WordPress
        run: |
          WP_ENV_CORE=WordPress/${{ matrix.wp-versions }} WP_ENV_PHP_VERSION=${{ matrix.php-versions }} npm run wp-env start
          npm run wp-env run cli wp core version
          npm run wp-env run cli wp cli info

      - name: Running e2e tests
        run: npm run test:e2e

  deploy:
    name: Deploy to WP.org
    runs-on: ubuntu-latest
    needs: [ test ]
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Use Node.js 14.x
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Npm install and build
        run: |
          npm ci
          npm run build

      - name: WordPress Plugin Deploy
        id: deploy
        uses: 10up/action-wordpress-plugin-deploy@stable
        with:
          generate-zip: true
        env:
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SLUG: custom-html-block-extension

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
          commitish: main

      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ steps.deploy.outputs.zip-path }}
          asset_name: ${{ github.event.repository.name }}.zip
          asset_content_type: application/zip
