name: Test

on:
  push:
    tags-ignore:
      - '**'
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-wp-versions: [
          '7.3', 'WordPress#5.9.5',
          '7.3', 'WordPress#6.0.3',
          '7.3', 'WordPress#6.1.1',
          '7.3', 'WordPress',
          '7.4', 'WordPress#5.9.5',
          '7.4', 'WordPress#6.0.3',
          '7.4', 'WordPress#6.1.1',
          '7.4', 'WordPress',
          '8.0', 'WordPress#5.9.5',
          '8.0', 'WordPress#6.0.3',
          '8.0', 'WordPress#6.1.1',
          '8.0', 'WordPress',
          '8.1', 'WordPress',
        ]
    name: PHP ${{ matrix.php-wp-versions[0] }}  / ${{ matrix.php-wp-versions[1] }} Test

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 14.x
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Npm install and build
        run: |
          npm ci
          npm run build

      - name: Composer install and set phpcs
        run: |
          composer install
          composer phpcs

      - name: Running lint check
        run: npm run lint

      - name: Install WordPress
        run: |
          WP_ENV_CORE=WordPress/${{ matrix.php-wp-versions[0] }} WP_ENV_PHP_VERSION=${{ matrix.php-wp-versions[1] }} npm run wp-env start
          npm run wp-env run cli wp core version
          npm run wp-env run cli wp cli info

      - name: Running e2e tests
        run: npm run test:e2e
